### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by rchastain** [thechampagne/rure-freebasic#1]
Hello!

I am trying to write a simple example using _rure.bi_ ([discussion on the FB forum](https://www.freebasic.net/forum/viewtopic.php?p=296646#p296646)).

Please could you help?

Regards.

Roland

**Comment by thechampagne** [comment]
Hi @rchastain !

You can check examples [here](https://github.com/rust-lang/regex/blob/master/regex-capi/ctest/test.c).

I'm afraid I didn't write it in fb but you can help and contribute to this repo.

By looking at the discussion it seems that you didn't link the library.
```sh
fbc -w all test.bas -p ./ -l rure
```
let me know what will happen.

**Comment by rchastain** [comment]
Hi! Thanks for your answer, and for the link the C example.

I will try again and come back if I find a solution. For now I can compile neither the FB nor the C example.

**Comment by rchastain** [comment]
I can compile the C example now. It seems that I wasn't using the right method for building the library.

Solution [here](https://github.com/rust-lang/regex/discussions/957).

**Comment by rchastain** [comment]
I can also compile the FB example, using your command.

**Comment by rchastain** [comment]
Here is a first working example.

```freebasic
' test1.bas (Rust regex library usage example) 

' 1. How to get librure.a
' -----------------------

/'
git clone https://github.com/rust-lang/regex
cd regex/regex-capi
cargo build --release
cd ../..              
cp regex/target/release/librure.a .
'/

' 2. How to get rure.bi
' ---------------------

/'
git clone https://github.com/thechampagne/rure-freebasic.git
cp rure-freebasic/src/rure.bi .
'/

' 3. How to build this example
' ----------------------------

/'
fbc -w all test1.bas -p . -l rure
'/

' Links
' -----
' https://github.com/rust-lang/regex/discussions/957
' https://github.com/thechampagne/rure-freebasic
' https://www.freebasic.net/forum/viewtopic.php?t=32048

#include "rure.bi"

#inclib "rure"

dim as rure ptr re

re = rure_compile_must("^\d{4}-\d{2}-\d{2}$")

dim as zstring*11 haystack => "0000-00-00"

dim as boolean match = rure_is_match(re, @haystack, len(haystack), 0)

print(match) ' true

haystack => "0000-00-0A"

match = rure_is_match(re, @haystack, len(haystack), 0)

print(match) ' false

rure_free(re)
```

Thank you for your help. If I write other examples, I will let you know.

**Comment by rchastain** [comment]
Hi! I finally wrote four examples. I put them here, in case someone is interested.

[rure-four-freebasic-examples.zip](https://github.com/thechampagne/rure-freebasic/files/10767206/rure-four-freebasic-examples.zip)
